version: "3.1"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 0
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: johnson@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 0
